package poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE,
	REPORT_MANAGEMENT_PAGE,
	VIDEO_MANAGEMENT_PAGE,
	
	HOME_SITE_PAGE,
	LOGIN_SITE_PAGE,
	REGISTER_SITE_PAGE,
	CATEGORY_SITE_PAGE,
	EDITPROFILE_SITE_PAGE,
	FAVORITE_SITE_PAGE,
	FORGOTPASSWORD_SITE_PAGE,
	CHANGEPASSWORD_SITE_PAGE
}
